### ISSUE TITLE
Add pigs to the game

### ISSUE THREAD

**Issue by KarinaKuznecova** [KarinaKuznecova/Game1-0#75]
There are already other animals in the game, so it shouldn't be a problem to add one more. 

Nothing special needed, let them just be exactly like rat, for example.

https://opengameart.org/content/pigs-rework

**Comment by LENHUTDUY-8120** [comment]
I really like this project! Can i try solve the issue? please assign me!

**Comment by KarinaKuznecova** [comment]
> I really like this project! Can i try solve the issue? please assign me!

Hi. Sure :) This will be great first issue. 
Feel free to ask anything, if you will have any questions

**Comment by LENHUTDUY-8120** [comment]
Excuse me. Can I change the scope of functions in class Animal? I want to override

**Comment by KarinaKuznecova** [comment]
Yes, if you think it will make code better. Can you share some details about changes?

**Comment by KarinaKuznecova** [comment]
Do you mean your new class Pig will override something from class Animals? If yes, then sure, do any changes.
