### ISSUE TITLE
Save map before loading another map

### ISSUE THREAD

**Issue by KarinaKuznecova** [KarinaKuznecova/Game1-0#79]
Tiny fix, but will make big change

Currently map is saved by pressing ctrl+s, but it should be also saved before loading another map. 

Should be easy, when secondary map is loading - just save previous map by calling gameMap.saveMap(). 

P.S. add logs about it

**Comment by ttnha** [comment]
Can I try slove the isssue ?
Please assign me?

**Comment by KarinaKuznecova** [comment]
Hi :)
Sure, assigned. Feel free to ask if you will have any questions.

**Comment by KarinaKuznecova** [comment]
Hi @ttnha 
Do you need any help with this issue? Are you still working on it?

**Comment by ttnha** [comment]
Sorry Sir, I can't find the solution to this problem

**Comment by KarinaKuznecova** [comment]
@ttnha 
That's ok :)

I will give you some tips:
In class Game.java - there is a method loadSecondaryMap. Inside this method we have all the logic how one map changes to another. 

There are two lines : 

```
        logger.info("Saving animals on previous map");
        gameMap.saveAnimals();
```

In this moment variable gameMap represents previous map. So if you add gameMap.saveMap() - previous map will be saved and you will solve the problem.
